---
version: "2.1"
services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK_SET=022 #optional
      - PLEX_CLAIM= #optional
      - TZ=Europe/Madrid
    volumes:
      - /data/config/plex:/config
      - /data/tvshows:/tv
      - /data/movies:/movies
    restart: unless-stopped

  transmission:
    container_name: transmission
    image: dperson/transmission
    restart: unless-stopped
    environment:
      - TZ=Europe/Madrid
      - TR_IDLE_SEEDING_LIMIT_ENABLED=true
      - TR_IDLE_SEEDING_LIMIT=600
      - TR_RATIO_LIMIT_ENABLED=true
      - TR_RATIO_LIMIT=4
      - TR_DOWNLOAD_DIR=/downloads
      - TR_INCOMPLETE_DIR_ENABLED=false
      - TR_RENAME_PARTIAL_FILES=true
      - TR_DHT_ENABLED=false
      - TR_PEX_ENABLED=false
      - USERID=1000
      - GROUPID=1000
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    volumes:
      - /data/config/transmission:/var/lib/transmission-daemon/info
      - /data/downloads/complete:/downloads
      - /data/downloads/temp:/var/lib/transmission-daemon/incomplete

